{
    "name": "SPX Job Card Core (Plant + Fleet)",
    "version": "19.0.1.0.0",
    "summary": "Unified maintenance Job Card with costs, LOTO, SLA & production loss; emergency auto-create; vendor bill sync; SOP gate",
    "category": "Maintenance",
    "author": "SP Nexgen Automind",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": [
        "base",
        "maintenance",
        "fleet",
        "hr",
        "account",
        "stock",
        "web",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/cron.xml",
        "views/jobcard_views.xml",
        "views/maintenance_request_views.xml",
        "views/maintenance_request_spare_views.xml",
        "views/jobcard_spares_views.xml",
        "views/checklist_views.xml",
        "views/jobcard_checklist_views.xml",
        "views/checklist_wizard_views.xml",
        "views/hr_employee_views.xml",
        "views/account_move_views.xml",
    ],
    "demo": [
        "data/demo.xml",
    ],
    "application": False,
    "installable": True,
}
