{
    'name': 'Website RMC Calculator',
    'version': '19.0.1.1.0',
    'summary': 'Popup calculator for RMC volume on website landing page',
    'author': 'AutoGenerated',
    'license': 'AGPL-3',
    'category': 'Website',
    'depends': ['website', 'crm', 'sale', 'website_sale'],
    'data': [
        'views/rmc_calculator_views.xml',
        'views/rmc_landing_page.xml',
        'views/rmc_simple_landing.xml',
        'data/website_rmc_data.xml',
        'views/snippets/rmc_snippet.xml',
    ],
    'assets': {
        'website.assets_frontend': [
            'website_rmc_calculator/static/src/js/popup_calc.js',
            'website_rmc_calculator/static/src/scss/rmc_calculator.scss',
        ],
        'website.assets_editor': [
            'website_rmc_calculator/static/src/js/snippet_editor_hook.js',
        ],
    },
    'installable': True,
    'application': False,
}
