{
    "name": "Gear On Rent",
    "version": "19.0.1.0.1",
    "author": "SmarterPeak",
    "license": "OEEL-1",
    "category": "Services/Rental",
    "website": "https://smarterpeak.com",
    "summary": "Rental and RMC blended production workflow with LOTO and NGT handling.",
    "depends": [
        "sale_management",
        "sale_renting",
        "project",
        "maintenance",
        "mrp",
        "account",
        "website",
        "helpdesk",
        "crm",
    ],
    "images": ["static/description/icon.png"],
    "data": [
        "data/sequence_data.xml",
        "data/crm_team_data.xml",
        "data/security/gear_on_rent_security.xml",
        "data/security/ir.model.access.csv",
        "data/cron.xml",
        "data/product_rmc_data.xml",
        "data/product_batching_data.xml",
        "data/batching_plant_demo_data.xml",
        "data/cleanup_optional_services.xml",
        "views/gear_on_rent_templates.xml",
        "views/batching_plant_templates.xml",
        "views/batching_plant_portal_templates.xml",
        "views/portal_templates.xml",
        "data/website_page_gear_on_rent.xml",
        "data/website_page_batching_plant.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
        "views/batching_master_calculator_views.xml",
        "views/rmc_work_order_views.xml",
        "views/log_views.xml",
        "views/annual_reconciliation_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu.xml",
        "views/batching_plant_master_views.xml",
        "views/prime_rate_log_views.xml",
        "views/cycle_reason_views.xml",
        "views/reason_views.xml",
        "views/wizard_views.xml",
        "views/workorder_views.xml",
        "views/stock_scrap_views.xml",
        "reports/qweb/report_daily_mo.xml",
        "reports/qweb/report_month_end.xml",
        "reports/qweb/report_invoice_templates.xml",
        "reports/qweb/report_annual_reconciliation.xml",
        "reports/qweb/report_batching_plant_quote.xml",
        "reports/qweb/report_ngt_request.xml",
        "data/mail_templates.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
