{
    "name": "RMC Commission Agent",
    "version": "19.0.1.0.0",
    "summary": "Manage commission agents across sales channels with portal visibility.",
    "author": "RMC",
    "website": "https://smarterpeak.com",
    "category": "Sales",
    "license": "LGPL-3",
    "depends": [
        "base",
        "sale",
        "sale_management",
        "stock",
        "account",
        "portal",
        "website",
        "contacts",
        "mail",
    ],
    "data": [
        "security/commission_agent_groups.xml",
        "security/portal_security.xml",
        "security/ir.model.access.csv",
        "views/commission_agent_views.xml",
        "views/sale_order_views.xml",
        "views/portal_templates.xml",
        "views/commission_agent_website_templates.xml",
        "data/commission_agent_website_data.xml",
    ],
    "demo": [
        "data/demo_data.xml",
    ],
    "installable": True,
    "application": False,
}
